# Generated by Django 5.0.3 on 2024-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('estadoActual', models.BooleanField(default=True)),
                ('estadoSalud', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=30)),
                ('fechaRescate', models.DateField(blank=True, null=True)),
                ('fechaAdopcion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
