# Generated by Django 5.0.3 on 2024-04-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('idAliado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=30, verbose_name='Nombre de la empresa')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo de la empresa')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono de la empresa')),
                ('tipoServicio', models.CharField(max_length=30, verbose_name='Tipo de servicio')),
                ('tipoProductos', models.CharField(max_length=30, verbose_name='Tipo de productos')),
            ],
        ),
    ]
