# Generated by Django 5.0.3 on 2024-04-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_aliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagenAnimal',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
