# Generated by Django 5.0.3 on 2024-04-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_animal_imagenanimal_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliado',
            name='imagenAliado',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagenAnimal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
