# Generated by Django 5.0.3 on 2024-04-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_aliado_imagenaliado_alter_animal_imagenanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('idConsejo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagenConsejo', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
