# Generated by Django 5.0.3 on 2024-04-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_consejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='numeroContacto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
