# Generated by Django 5.0.3 on 2024-04-30 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_animal_numerocontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliado',
            old_name='tipoProductos',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='aliado',
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='aliado',
            name='ofrece',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Producto o servicios'),
            preserve_default=False,
        ),
    ]
